BASE_FOLDER = "/experiments/sa_plusplus/"
MODELS_BASE_FOLDER = BASE_FOLDER + "models/"
RESULTS_BASE_FOLDER = BASE_FOLDER + "results/"
DATASETS_BASE_FOLDER = BASE_FOLDER + "datasets/"

DSA_BATCH_SIZE = 1000
